export {default as clamp} from './clamp'
export {default as comp} from './comp'
export {default as flip} from './flip'
export {default as map} from './map'
export {default as merge} from './merge'
export {default as tap} from './tap'
